kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "elixir-builder"
spec:
  runPolicy: "Serial" 
  triggers:
    - type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/brianorwhatever/s2i-elixir.git"
    contextDir: 1.6/otp-21
  strategy: 
    dockerStrategy:
      dockerfilePath: Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "elixir:1.6-otp-21"
